# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [118]:
import numpy as np

In [119]:
#Создайте матрицу 3 на 3, заполненную числами от 1 до 9
A1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
# Создаем еденичную матрицу с помощью функции:
A2 = np.eye(3)
A2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [121]:
# сложение:
A3 = A1 + A2
A3

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [122]:
# записываем вектор:
a = np.array([1 ,2 ,3])
a

array([1, 2, 3])

In [123]:
A4 = A3@a
A4

array([15., 34., 53.])

Вычислить транспонированную матрицу  𝐴𝑇 от полученной в результате прибавления матрицы

In [124]:
np.transpose(A3)

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [125]:
A5 = np.linalg.inv(A3)
A5

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01,  2.22044605e-17],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [126]:
m = np.array([[2, 2],[1, 3]])
m

array([[2, 2],
       [1, 3]])

In [127]:
# собственные значения:
np.linalg.eigvals(m)

array([1., 4.])

собственные вектора:

In [128]:
res = np.linalg.eig(m)
res2 = res[1]

In [129]:
res3 = np.transpose(res2)
res3

array([[-0.89442719,  0.4472136 ],
       [-0.70710678, -0.70710678]])

In [130]:
v1 = res3[0]/res3[0, 1]
v1

array([-2.,  1.])

In [131]:
v2 = res3[1]/res3[1, 1]
v2

array([1., 1.])

In [132]:
# вариант 2 
[res3[i]/res3[[i], 1] for i in range(len(res3))]

[array([-2.,  1.]), array([1., 1.])]

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [133]:
h = 0
while h != 1:
    mas = np.random.randint(-10, 10, size=(3,3))
    h = np.linalg.det(mas)
mas


array([[-2, -8, -9],
       [ 1,  6, -2],
       [-1, -3, -8]])

In [134]:
np.linalg.det(mas)


1.0